name: dotnet Application

on:
  push:
    branches: [ master, codecov ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-2

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run Unit Test
      run: dotnet test Amazon.QLDB.Driver.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    #- name: Integration Test
      #run: dotnet test Amazon.QLDB.Driver.IntegrationTests --no-restore --verbosity normal --settings Amazon.QLDB.Driver.IntegrationTests/.runsettings

    - name: Uploade to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ../../Amazon.QLDB.Driver.Tests/coverage.net48.opencover.xml
        flags: unittests # optional
        name: codecov-umbrella # optional
        verbose: true # optional (default = false
